# list the windows you want to open below in the following syntax
# referenceName: (this will be used in the cli)
#   - windowName (no spaces)
#   - url 1
#   - url 2
#   - etc.

# example you can delete
Media Window:
  - Media
  - https://www.youtube.com/
  - https://open.spotify.com/